# Generated by Django 3.2.9 on 2021-12-02 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweeterApp', '0002_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tweeterApp.tweet'),
        ),
    ]
